FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY api/requirements.txt .

RUN pip3 install torch==2.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

RUN pip3 install --no-cache-dir -r requirements.txt

COPY api /app/api

RUN mkdir -p /app/downloads

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
