services:
  api:
    build:
      context: .
      dockerfile: Dockerfile # 或 Dockerfile.slim，取决于是否需要GPU支持
    volumes:
      - ./:/app/

    ports:
      - "8600:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8601:8501"
    depends_on:
      - api
    command: streamlit run frontend/main.py
