version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./data:/app/downloads
      - ./data:/app/transcriptions.db
    environment:
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL=medium
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --workers 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL=medium
    depends_on:
      - api
    command: streamlit run main.py
