FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY api/requirements-cuda.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY api /app/api

RUN mkdir -p /app/downloads

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
