version: '3.8'

services:
  api:
    image: saltfishc/transcribe-it-api:latest-cuda
    environment:
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL=medium
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    image: saltfishc/transcribe-it-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - api
